security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\Utilisateur:
            algorithm: auto
    providers:
        database_users:
            entity: { class: App\Entity\Utilisateur, property: login }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            stateless: true
            anonymous: true
            provider: database_users
            json_login:
                check_path: /authentication_token
                username_path: login
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        refresh:
            pattern: ^/token/refresh
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/api/ateliers, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/getCurrentUser, roles: [ROLE_USER] }
        - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
